.TH fag 1 "16 February 2018" "1.2" "User Commands"
.hy 0
.SH NAME
fag \- daemonize program after a regular expression pattern was matched (ForkAfterGrep)
.
.SH SYNOPSIS
.B fag
.RI [ OPTIONS ]
.I PATTERN
.I PROGRAM
.RI [ ARGUMENTS .\|.\|.]
.br
.SH DESCRIPTION
.B fag
uses
.B grep
to search the output of
.IR PROGRAM
for the regular expression
.IR PATTERN
and daemonizes it when a match is found. The PID is then returned on stdout. 
.SH OPTIONS
.SS "Behaviour Changing Options"
.TP
.BI \-t " SECONDS" "\fR
Set a timeout of
.I SECONDS
seconds.
.TP
.BR \-k " [" \fISIGNAL\fP "]
If given, send a signal to
.IR PROGRAM .
.I SIGNAL
defaults to 
.BR SIGTERM " (15)."
Right now, only decimal notation is implemented.
.TP
.BR \-r
Search
.IR PATTERN
on
.BR stderr
instead of 
.BR stdout .
.TP
.BI \-l " FILE "
Log
.IR PROGRAM\fR's
.BR stdout
to
.IR FILE .
The file will be opened in append mode and created with permissions 0600 if it doesn't exist.
.TP
.BI \-L " FILE "
Same as 
.BR \-l
but logs
.IR PROGRAM\fR's
.BR stderr .
.TP
.BR \-V
Be verbose; print program's
.BR stdout
(or stderr if
.BR \-r
is set) to stderr. 
.SS "Generic Program Information"
.TP
.B \-h
Output a short usage message and exit.
.TP
.BR \-v
Display version and copyright information and exit.
.SS "Supported grep Options"
.TP
.BR \-E ", " \-F ", " \-G ", " \-P
Matcher selection switches for extended regular expressions, fixed strings, basic regular expressions (default) or Perl-compatible regular expressions. You may only supply one of them.
.TP
.BR \-i ", " \-w ", " \-x ", " \-U
Matching control switches for ignore case distinctions, whole words only, whole lines only and treat as binary. 
.TP
.BR \-Z ", " \-J
Decompression switches for 
.IR gzip (1)
and 
.IR bzip2 (1).
Not widely supported; check your \fBgrep\fR's capabilities.
.SH EXIT STATUS
If
.IR PATTERN
was found, 0 is returned. Otherwise, the exit status follows the BSD guideline outlined in 
.B #include <sysexits.h>
if the error occured from within
.B fag
or in case the chid process exits prematurely, its exit code is inherited. Notably, \fI69\fP is returned when the timeout is reached.
.SH BUGS
.SS Known Bugs
if grep gets killed (e.g. `killall grep'), fag should terminate. 
.SS Reporting Bugs
Please report bugs and patches to the issue tracker at https://github.com/girst/forkaftergrep/. 
.SH NOTES
.IR SIGNAL
needs to be given as an integer. implementing mnemonics is dirty and not very portable; maybe support in the future.
.PP
Since 1.1, if
.B fag
gets interrupted or terminated, 
.BR SIGTERM
is sent to 
.IR PROGRAM.
.PP
In 1.2 the command line switch 
.B \-e was renamed to 
.B \-r
to avoid overloading 
.B grep\fR's own switches.
.SH COPYRIGHT
Copyright 2017 Tobias Girstmair. This is free software; see https://www.gnu.org/licenses/gpl-3.0.html for conditions.
.SH AUTHOR
Tobias Girstmair (https://gir.st)
